# Generated by Django 3.2.4 on 2021-09-01 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionSeguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presentacion', models.DateField()),
                ('fecha_sustentacion', models.DateField()),
                ('ultima_edicion', models.DateTimeField()),
                ('proyecto_tesis', models.FileField(null=True, upload_to='proyecto_tesis')),
                ('informe_final', models.FileField(null=True, upload_to='informe_final')),
                ('estado', models.CharField(max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionSeguridad.alumno')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionSeguridad.docente')),
            ],
        ),
        migrations.CreateModel(
            name='JuradoTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('documento', models.FileField(null=True, upload_to='plan_tesis_observado')),
                ('estado', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionSeguridad.docente')),
                ('plan_tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTesis.plantesis')),
            ],
            options={
                'unique_together': {('docente', 'plan_tesis')},
            },
        ),
    ]
