# Generated by Django 3.2.4 on 2021-08-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionSeguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presentacion', models.DateField()),
                ('fecha_sustentacion', models.DateField()),
                ('ultima_edicion', models.DateTimeField()),
                ('documento', models.FileField(null=True, upload_to='plan_tesis')),
                ('estado', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionSeguridad.alumno')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionSeguridad.docente')),
            ],
        ),
    ]
