# Generated by Django 3.2.4 on 2021-09-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantesis',
            name='estado',
            field=models.CharField(default='CREADO', max_length=10),
        ),
        migrations.AlterField(
            model_name='plantesis',
            name='fecha_sustentacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plantesis',
            name='informe_final',
            field=models.FileField(null=True, upload_to='plan_tesis'),
        ),
        migrations.AlterField(
            model_name='plantesis',
            name='proyecto_tesis',
            field=models.FileField(null=True, upload_to='plan_tesis'),
        ),
        migrations.AlterField(
            model_name='plantesis',
            name='ultima_edicion',
            field=models.DateTimeField(null=True),
        ),
    ]
