# Generated by Django 3.2.4 on 2021-08-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionSeguridad', '0001_initial'),
        ('gestionTesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuradoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('documento', models.FileField(null=True, upload_to='plan_tesis_observado')),
                ('estado', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionSeguridad.docente')),
                ('plan_tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTesis.plantesis')),
            ],
            options={
                'unique_together': {('docente', 'plan_tesis')},
            },
        ),
    ]
