# Generated by Django 3.1.7 on 2021-09-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTesis', '0003_auto_20210907_2147'),
        ('gestionTesis', '0002_auto_20210907_1459'),
    ]

    operations = [
    ]
