# Generated by Django 3.2.4 on 2021-09-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTesis', '0005_auto_20210907_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juradotesis',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='juradotesis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plantesis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
