# Generated by Django 3.2.4 on 2021-08-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_matricula', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=40)),
                ('nombres', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('facultad', models.CharField(max_length=40)),
                ('escuela', models.CharField(max_length=40)),
                ('ciclo_academico', models.CharField(max_length=4)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=40)),
                ('nombres', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
