# Generated by Django 3.2.6 on 2021-08-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionSeguridad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jurado',
            new_name='Docente',
        ),
        migrations.DeleteModel(
            name='Asesor',
        ),
    ]
