# Generated by Django 3.2.4 on 2021-09-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionSeguridad', '0002_auto_20210830_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
