# Generated by Django 3.2.6 on 2021-08-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionSeguridad', '0002_auto_20210829_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
