# Generated by Django 3.2.6 on 2021-09-06 04:11

from django.db import migrations


def load_facul(apps, schema_editor):
    Facultad = apps.get_model("gestionSeguridad", "Facultad")
    facul0 = Facultad(id=0,descripcion='Facultad de Ciencias Biológicas')
    facul0.save()
    facul1 = Facultad(id=1,descripcion='Facultad de Farmacia y Bioquímica')
    facul1.save()
    facul2 = Facultad(id=2,descripcion='Facultad de Educación y Ciencias de la Comunicación')
    facul2.save()
    facul3 = Facultad(id=3,descripcion='Facultad de Medicina')
    facul3.save()
    facul4 = Facultad(id=4,descripcion='Facultad de Estomatología')
    facul4.save()
    facul5 = Facultad(id=5,descripcion='Facultad de Ciencias Sociales')
    facul5.save()
    facul6 = Facultad(id=6,descripcion='Facultad de Ciencias Físicas y Matemáticas')
    facul6.save()
    facul7 = Facultad(id=7,descripcion='Facultad de Ciencias Económicas')
    facul7.save()
    facul8 = Facultad(id=8,descripcion='Facultad de Derecho y Ciencias Políticas')
    facul8.save()
    facul9 = Facultad(id=9,descripcion='Facultad de Ingeniería')
    facul9.save()
    facul10 = Facultad(id=10,descripcion='Facultad de Ingeniería Química')
    facul10.save()
    facul11 = Facultad(id=11,descripcion='Facultad de Enfermería')
    facul11.save()
    facul12 = Facultad(id=12,descripcion='Facultad de Ciencias Agropecuarias')
    facul12.save()

def delete_facul(apps, schema_editor):
    Facul = apps.get_model("gestionSeguridad", "Facultad")
    Facul.objects.all().delete()
    

    
class Migration(migrations.Migration):

    dependencies = [
        ('gestionSeguridad', '0003_auto_20210905_2310'),
    ]

    operations = [        
        migrations.RunPython(load_facul),
    ]
