# Generated by Django 3.1.7 on 2021-09-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionSeguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=11)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=30)),
                ('gerente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('estado', models.CharField(default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPracticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tramite', models.DateField()),
                ('derecho_tramite', models.FileField(upload_to='plan_practica/')),
                ('plan_practicas', models.FileField(upload_to='plan_practica/')),
                ('fecha_presentacion', models.DateField(null=True)),
                ('informe_final', models.FileField(null=True, upload_to='plan_practicas/')),
                ('resolucion', models.FileField(null=True, upload_to='plan_practicas/')),
                ('estado', models.CharField(default='CREADO', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionSeguridad.alumno')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionSeguridad.docente')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPracticas.contacto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPracticas.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPracticas.empresa'),
        ),
    ]
