# Generated by Django 3.1.7 on 2021-09-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPracticas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='apellidos',
        ),
    ]
