# Generated by Django 3.1.7 on 2021-09-08 02:56

from django.db import migrations


class Migration(migrations.Migration):


    def load_empresa(apps, schema_editor):
        Empresa = apps.get_model("gestionPracticas", "Empresa")
        emp0 = Empresa(id=0,razon_social='null',ruc="null",direccion="null",ciudad="null",gerente="null",telefono="null", estado="Desactivo")
        emp0.save()
    
    

    dependencies = [
        ('gestionPracticas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_empresa),   
    ]
