# Generated by Django 3.1.7 on 2021-09-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    def load_contacto(apps, schema_editor):
        Contacto = apps.get_model("gestionPracticas", "Contacto")
        cont0 = Contacto(id=0,nombres='null',cargo='null',telefono="null",email="null",estado="Desactivo",empresa_id=0)
        cont0.save()

    dependencies = [
        ('gestionPracticas', '0003_auto_20210907_2156'),
    ]

    operations = [
        migrations.RunPython(load_contacto),
    ]
