# Generated by Django 3.1.7 on 2021-09-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPracticas', '0003_remove_contacto_apellidos'),
        ('gestionPracticas', '0004_auto_20210907_2212'),
    ]

    operations = [
    ]
